c>generate [ makes  a key ]
c>whitelist [ acc name ] 
c>unwhitelist [ acc name ]
c>annoue [ message]
c>database [ shows cc whitelisted database ] 
c>temp-whitelist [ acc name ] [time ] [ discord account ] 
